### PR TITLE
fix: readiness probe on historical

### LINKED ISSUE #97: Default readiness on historicals breaks operator.
In pr #72 , defaults probes are set for various components.

This breaks the operator because while `/druid/historical/v1/readiness` is just fine to call `/druid/historical/v1/loadstatus` is a privileged call that requires authentication. Since it places this readinessProbe by default if you don't have one, the only way to disable it is to hard wire one yourself to another call.

```
curl -vvv http://127.0.0.1:4124/druid/historical/v1/readiness
HTTP/1.1 200 OK

curl -vvv http://127.0.0.1:4124/druid/historical/v1/loadstatus
HTTP/1.1 401 Unauthorized
```

### PR DESCRIPTION
**Pull request by cyril-corbon**
Fixes #97 

### Description

1. change historical readiness path to `/druid/historical/v1/readiness`  
  Both path has similar purpose. https://druid.apache.org/docs/latest/operations/api-reference/#historical
  ```
  Similar to /druid/historical/v1/loadstatus, but instead of returning JSON with a flag, responses 200 OK if segments in the local cache have been loaded, and 503 SERVICE UNAVAILABLE, if they haven't.
  ```
2. add defaultProbes bool in druid spec to true by default 
3. update docs and document the issue with middle manager less until we add test case and a fix

<hr>

This PR has:
- [x] been tested on a real K8S cluster to ensure creation of a brand new Druid cluster works.
- [x] been tested for backward compatibility on a real K*S cluster by applying the changes introduced here on an existing Druid cluster. If there are any backward incompatible changes then they have been noted in the PR description.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added documentation for new or modified features or behaviors.

<hr>

##### Key changed/added files in this PR
 * `controllers/druid/handler.go`
 * `docs/features.md`
 *  `chart/templates/crds/druid.apache.org_druids.yaml`
 * `config/crd/bases/druid.apache.org_druids.yaml`

### CODE REVIEW

**Review by itamar-marom — APPROVED** [review]

File: apis/druid/v1alpha1/druid_types.go [hunk 1]
```diff
@@ -241,6 +241,12 @@ type DruidSpec struct {
 	// +kubebuilder:default:=true
 	RollingDeploy bool `json:"rollingDeploy"`
 
+	// DefaultProbes If set to true this will add default probes (liveness / readiness / startup) for all druid components
+	// but it won't override existing probes
+	// +optional
+	// +kubebuilder:default:=false
```
Comment (itamar-marom) [inline apis/druid/v1alpha1/druid_types.go:247]: I think it should be the default unless people want to disable it. Because it should work best "out of the box"

File: controllers/druid/handler.go [hunk 2]
```diff
@@ -1143,7 +1143,7 @@ func setLivenessProbe(nodeSpec *v1alpha1.DruidNodeSpec, m *v1alpha1.Druid) *v1.P
 	livenessProbe := updateDefaultPortInProbe(
 		firstNonNilValue(nodeSpec.LivenessProbe, m.Spec.LivenessProbe).(*v1.Probe),
 		nodeSpec.DruidPort)
-	if livenessProbe == nil {
+	if livenessProbe == nil && m.Spec.DefaultProbes == true {
```
Comment (itamar-marom) [inline controllers/druid/handler.go:1146]: you don't need the "== true"
also on the below ones

File: docs/features.md [hunk 3]
```diff
@@ -110,7 +110,12 @@ There are two scopes you can add additional container:
 ## Default Yet Configurable Probes
 The operator create the Deployments and StatefulSets with a default set of probes for each druid components.
 These probes can be overriden by adding one of the probes in the `DruidSpec` (global) or under the
-`NodeSpec` (component-scope). 
+`NodeSpec` (component-scope).
+
+:warning: Do not enable this feature if you have the `kubernetes-overlord-extensions` enabled also named [middle manager less druid in k8s](https://druid.apache.org/docs/latest/development/extensions-contrib/k8s-jobs/)
```
Comment (cyril-corbon) [inline docs/features.md:115]:
```suggestion
:warning: Do not enable this feature if you have the `kubernetes-overlord-extensions` enabled also named [middle manager less druid in k8s](https://druid.apache.org/docs/latest/development/extensions-contrib/k8s-jobs/)
refer to this issue: https://github.com/datainfrahq/druid-operator/issues/97#issuecomment-1687048907
```

**Review by itamar-marom — APPROVED** [review]
Did you use the `make api-docs` command for the API generation? If so great. If not, you should use it to generate the API specification.
Approved anyway :)

**Comment by cyril-corbon** [comment]
> Did you use the `make api-docs` command for the API generation? If so great. If not, you should use it to generate the API specification. Approved anyway :)

yes I used `make api-docs`
